baseURL: https://tidyblog.netlify.app/
defaultContentLanguage: en
hasCJKLanguage: yes
languageCode: en
paginate: 5
theme: hugo-theme-texify
title: The Tidy Blog for Workforce Analytics
disqusShortname: ''
googleAnalytics: ''
pygmentsUseClasses: yes
author:
  name: Vicenc Fernandez
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
menu:
  main:
    - identifier: post
      name: Home
      url: /
      weight: 1
    - identifier: archives
      name: Archives
      url: /post/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
params:
  customCSS: []
  dateFormat: '2006-01-02'
  description: an example site for hugo theme TeXify
  enableFullRSS: yes
  enableHanEmph: yes
  enableMathjax: yes
  favicon: /favicon.ico
  footnote: Follow me on <a class=link href=https://github.com/vicencfernandez>GitHub</a>,
    <a class=link href=https://twitter.com/vicencfernandez>Twitter</a> or <a class=link
    href=/index.xml>RSS</a> | <a class=link href=https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
    target=_blank rel=noopener>CC BY-NC-SA 4.0</a>
  keywords:
    - hugo
    - latex
    - theme
